version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - crm-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGO_URI=${MONGO_URI}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=your-jwt-secret
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - crm-network

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - crm-network

  vendor:
    build:
      context: ./vendor-simulator
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - BACKEND_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - crm-network

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db
    networks:
      - crm-network

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - crm-network

volumes:
  mongo_data:
  rabbitmq_data:

networks:
  crm-network:
    driver: bridge
