[build]
  # Build command for static export
  command = "cd frontend && npm ci && npm run build"
  # Publish directory for static files
  publish = "frontend/out"

[build.environment]
  # Disable Next.js serverless functions
  NEXT_TELEMETRY_DISABLED = "1"

# Redirect rules for SPA routing
# Specific API auth redirects first
[[redirects]]
  from = "/api/auth/error"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/api/auth/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/api/*"
  to = "/404.html"
  status = 404

# Catch-all for SPA routing (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for cache busting
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
