[build]
  # Build command for static export
  command = "cd frontend && npm ci && npm run build"
  # Publish directory for static files
  publish = "frontend/out"

[build.environment]
  # Disable Next.js serverless functions
  NEXT_TELEMETRY_DISABLED = "1"

# Redirect rules for SPA routing
[[redirects]]
  from = "/api/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
