services:
  - type: web
    name: xeno-crm-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        value: https://xeno-crm-frontend.onrender.com
      - key: NEXTAUTH_SECRET
        value: your-secret-key-here
      - key: NEXT_PUBLIC_API_URL
        value: https://backend-production-05a7e.up.railway.app/api/v1
